server:
  port: 8761

spring:
  profiles:
    active: dev
  application:
    name: zivdah-eureka-server

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: WARN