server:
  port: 8002
  address: 0.0.0.0

spring:
  application:
    name: zivdah-auth-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/zivdahDB
    username: postgres
    password: root
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  flyway:
    url: jdbc:postgresql://localhost:5432/zivdahDB
    user: postgres
    password: root
    locations: classpath:db/migration
    baseline-on-migrate: true   # <-- Add this


  mail:
    host: smtp.gmail.com
    port: 587
    username: uravi0704@gmail.com
    password: <GMAIL_APP_PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

logging:
  level:
    org.springframework.security: DEBUG



jwt:
  secret: my_super_secret_key_that_is_at_least_32_characters_long_123456