server:
  port: 8003

spring:
  application:
    name: zivdah-product-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/zivdahDB
    username: postgres
    password: root
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  flyway:
    url: jdbc:postgresql://localhost:5432/zivdahDB
    user: postgres
    password: root
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6380

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    io.r2dbc: DEBUG
